### ISSUE TITLE
Questions about thunderbird dataset

### ISSUE THREAD

**Issue by Xnightwish** [YifeiLin0226/FastLogAD#1]
I downloaded thunderbird dataset as per the link you provided and placed it in the specified location, but the code is not able to parse the encoding format of thunderbird, it seems to be US-ASCII encoding, I tried to convert the encoding format to UTF-8 to satisfy the code but it seems that the conversion is failing, I would like to consult the author on how he dealt with this issue.

**Comment by Xnightwish** [comment]
I tried again today and thunderbird is still coding errors, does the author have any solution for this?

**Comment by YifeiLin0226** [comment]
Hi, could you please show the output error messages?

**Comment by 2623493469** [comment]
> Hi, could you please show the output error messages?

![123](https://github.com/YifeiLin0226/FastLogAD/assets/82094957/835999ed-31c9-4bcb-b5e8-b2bdec2772da)
Ok bro, I downloaded the thunderbird dataset from the link you provided and changed its name to thunderbird_20M, but when I run it, it reports the error as shown.
![Uploading 234.png…]()

**Comment by Xnightwish** [comment]
> Hi, could you please show the output error messages?

Ok bro, I downloaded the thunderbird dataset from the link you provided and changed its name to thunderbird_20M, but when I run it, it reports the error as shown.

![123](https://github.com/YifeiLin0226/FastLogAD/assets/82094957/499ae602-f69b-4aeb-847e-57259574ad08)

![234](https://github.com/YifeiLin0226/FastLogAD/assets/82094957/79b0106e-395f-46bf-8001-6045b9df7914)

**Comment by YifeiLin0226** [comment]
I see, Thunderbird_20M.log isn't the original Thunderbird.log, I did the sampling adopted from LogBert for baseline comparisons. https://github.com/HelenGuohx/logbert/blob/main/TBird/data_process.py, sorry I didn't mention that in the project page

**Comment by Xnightwish** [comment]
> I see, Thunderbird_20M.log isn't the original Thunderbird.log, I did the sampling adopted from LogBert for baseline comparisons. https://github.com/HelenGuohx/logbert/blob/main/TBird/data_process.py, sorry I didn't mention that in the project page

Good brother, thanks for the guidance.
